algoritmo "exercicio2"
// Função : algoritmo que imprime a tabuada de um número informado pelo usuário
// Autor : rayssa de castro
// Data : 23/08/2021
// Seção de Declarações 
var
num, resul,cont:inteiro
inicio
// Seção de Comandos 
escreval("*********ESTE PROGRAMA CALCULA A TABUADA**********")
escreval("Digite um numero")
leia(num)

para cont de 1 ate 10 faca
    resul<- num*cont
    escreval(num, " X", cont, " = ", resul)
fimpara

fimalgoritmo
