algoritmo "exercicio7"
// Função : calcular numeros, até que o numero digitado seja zero
// Autor :rayssa de castro
// Data : 23/08/2021
// Seção de Declarações 
var
num,total:inteiro
inicio
// Seção de Comandos 
escreval("--------este programa se encerra quando você digitar 0(zero)---------")

repita
   escreval("Digite o numero")
   leia(num)
    total<-num+total
ate num=0


escreval("A soma dos numeros é ", total)


fimalgoritmo
