algoritmo "area_do_triangulo"
// Função : calcular da area do triangulo
// Autor : rayssa castro
// Data : 02/03/2021
// Seção de Declarações 
var
   base ,area,alt: real

inicio
// Seção de Comandos 
escreval("digite a base do triangulo: ")
leia(base)
escreval ("digite a altura do triangulo retangulo:")
leia(alt)
area<-(base*alt)/2
escreval("a area do triangulo retangulo e: ", area, "m2")


fimalgoritmo
